name: 'Terraform'

on:
  push:
    branches:
      - dev
      - main
    paths:
      - terraform/**
  workflow_dispatch:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cred replacement
      run: |
        sed -i "s/REGUSER/${{ github.actor }}/" container_app.tf
        sed -i "s/REGPASS/${{ secrets.MY_PAT }}/" container_app.tf

    - name: Terraform Plan
      run: |
        terraform init
        terraform plan -input=false
    
  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Cred replacement
      run: |
        sed -i "s/REGUSER/${{ github.actor }}/" container_app.tf
        sed -i "s/REGPASS/${{ secrets.MY_PAT }}/" container_app.tf

    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -input=false -auto-approve
        